{
  "formatVersion": "1.1",
  "component": {
    "group": "origin.cyn_hc.astruim_c.blackcell_s",
    "module": "voidapi",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voidapi-0.1.2.jar",
          "url": "voidapi-0.1.2.jar",
          "size": 6135,
          "sha512": "03e7d7c043cd20209b244bffca84254f6bbd562fc173354d5f87847efa95eeac1775bcf90801bcbb801d706b897fe9e1782451d6c7be0e95670b300237328499",
          "sha256": "1070e760fb6f8f899057b70cf25ad12f0d67d914e5a3c097a25c5c1fe4e47214",
          "sha1": "7ee8cf5894d93959944f161d5040a9a22b1bd10e",
          "md5": "381915d8faa981feaa413981f917e041"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "voidapi-0.1.2.jar",
          "url": "voidapi-0.1.2.jar",
          "size": 6135,
          "sha512": "03e7d7c043cd20209b244bffca84254f6bbd562fc173354d5f87847efa95eeac1775bcf90801bcbb801d706b897fe9e1782451d6c7be0e95670b300237328499",
          "sha256": "1070e760fb6f8f899057b70cf25ad12f0d67d914e5a3c097a25c5c1fe4e47214",
          "sha1": "7ee8cf5894d93959944f161d5040a9a22b1bd10e",
          "md5": "381915d8faa981feaa413981f917e041"
        }
      ]
    }
  ]
}
