{
  "formatVersion": "1.1",
  "component": {
    "group": "origin.cyn_hc.astruim_c.blackcell_s",
    "module": "voidapi",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voidapi-0.1.1.jar",
          "url": "voidapi-0.1.1.jar",
          "size": 4900,
          "sha512": "7e8baf0bd63403f0ad9e23c085462a02c568865f189f70a94298a9dd8d4f00048368a316be15507493e9ae0e8ebfbd6f1ea56088f4c6bc659171dff4e95e107d",
          "sha256": "56de681edff46cc9e7f06d8604c1f08fdc787e5a04ba092ea8c076665e06c54a",
          "sha1": "ff43b73ebae5caefd146c431b36894bd53f2ef26",
          "md5": "419a64b0b2c8062a9324f2872c947cf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "voidapi-0.1.1.jar",
          "url": "voidapi-0.1.1.jar",
          "size": 4900,
          "sha512": "7e8baf0bd63403f0ad9e23c085462a02c568865f189f70a94298a9dd8d4f00048368a316be15507493e9ae0e8ebfbd6f1ea56088f4c6bc659171dff4e95e107d",
          "sha256": "56de681edff46cc9e7f06d8604c1f08fdc787e5a04ba092ea8c076665e06c54a",
          "sha1": "ff43b73ebae5caefd146c431b36894bd53f2ef26",
          "md5": "419a64b0b2c8062a9324f2872c947cf9"
        }
      ]
    }
  ]
}
