{
  "formatVersion": "1.1",
  "component": {
    "group": "origin.cyn_hc.astruim_c.blackcell_s",
    "module": "voidapi",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voidapi-0.1.3.jar",
          "url": "voidapi-0.1.3.jar",
          "size": 11000,
          "sha512": "decb231477185c7a52e778ba608275431f93050ee91dcaebda28dbac71a10b8905224128be07d8f7adecaf151c1f437d7d6c24d066793b24fbbdcd46dd590b7b",
          "sha256": "d432257737dfff2c4d395f128faa42b138edde923641accf4ddcd660b527dd9f",
          "sha1": "6e515ba5316f3b96c8dbf0ef228cfc3cea9c6d5d",
          "md5": "a91a05ce303009b197922e7f289ae21c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "voidapi-0.1.3.jar",
          "url": "voidapi-0.1.3.jar",
          "size": 11000,
          "sha512": "decb231477185c7a52e778ba608275431f93050ee91dcaebda28dbac71a10b8905224128be07d8f7adecaf151c1f437d7d6c24d066793b24fbbdcd46dd590b7b",
          "sha256": "d432257737dfff2c4d395f128faa42b138edde923641accf4ddcd660b527dd9f",
          "sha1": "6e515ba5316f3b96c8dbf0ef228cfc3cea9c6d5d",
          "md5": "a91a05ce303009b197922e7f289ae21c"
        }
      ]
    }
  ]
}
