{
  "formatVersion": "1.1",
  "component": {
    "group": "origin.cyn_hc.astruim_c.blackcell_s.voidgradle",
    "module": "voidgradle",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voidgradle-0.1.0.jar",
          "url": "voidgradle-0.1.0.jar",
          "size": 4985,
          "sha512": "8cb98aa0eaaa8a76119b8cbfde5c79dc27040c83abf145ca7c64806c4efbe5caaa51127afde601913cb89f32f75753b70f4ae9aef1d65f3a3dd435240cb94097",
          "sha256": "bafe69e716514a6adb41223d4a6ce1fbd2550693c2b167a1ed0870848debf29a",
          "sha1": "dafc5ca91cc23825ee1ea0dc5d69cb66a61480df",
          "md5": "28b1e79d0a05f1c74794241fd6adeb43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "voidgradle-0.1.0.jar",
          "url": "voidgradle-0.1.0.jar",
          "size": 4985,
          "sha512": "8cb98aa0eaaa8a76119b8cbfde5c79dc27040c83abf145ca7c64806c4efbe5caaa51127afde601913cb89f32f75753b70f4ae9aef1d65f3a3dd435240cb94097",
          "sha256": "bafe69e716514a6adb41223d4a6ce1fbd2550693c2b167a1ed0870848debf29a",
          "sha1": "dafc5ca91cc23825ee1ea0dc5d69cb66a61480df",
          "md5": "28b1e79d0a05f1c74794241fd6adeb43"
        }
      ]
    }
  ]
}
