{
  "formatVersion": "1.1",
  "component": {
    "group": "origin.cyn_hc.astruim_c.blackcell_s",
    "module": "voidgradle",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voidgradle-0.1.0.jar",
          "url": "voidgradle-0.1.0.jar",
          "size": 4985,
          "sha512": "71e1830705adf3457545e0b9fd2be16864c960b3d5cc169577515a6431354cd1dfb5d4616dc100ef5cd75685bf1ea79a26869a6c75642f1ae19faadcc21022fb",
          "sha256": "c15bcba30425f6423917a5f14dd144e772be2c59c4576b23ae4d94694d9bc54d",
          "sha1": "5fb41ee491f6f6869a5ec6d58bf21c7545fbcf95",
          "md5": "e150a7744d16eed79e58bf49ea883862"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "voidgradle-0.1.0.jar",
          "url": "voidgradle-0.1.0.jar",
          "size": 4985,
          "sha512": "71e1830705adf3457545e0b9fd2be16864c960b3d5cc169577515a6431354cd1dfb5d4616dc100ef5cd75685bf1ea79a26869a6c75642f1ae19faadcc21022fb",
          "sha256": "c15bcba30425f6423917a5f14dd144e772be2c59c4576b23ae4d94694d9bc54d",
          "sha1": "5fb41ee491f6f6869a5ec6d58bf21c7545fbcf95",
          "md5": "e150a7744d16eed79e58bf49ea883862"
        }
      ]
    }
  ]
}
