{
  "formatVersion": "1.1",
  "component": {
    "group": "origin.cyn_hc.astruim_c.blackcell_s",
    "module": "voidgradle",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voidgradle-0.1.0.jar",
          "url": "voidgradle-0.1.0.jar",
          "size": 5057,
          "sha512": "070841ac9899df3170eef9d0ddf0f71ef8ac2024c311b064a337069710ed39deb4c4c59076189c655939b82b8662460447179b7ad97820f779d6e10d87cd52c6",
          "sha256": "0fc34bd0b4e8d1d0d3147312f2b84fa3c2a7c253729c45d52e6928f9044a58e1",
          "sha1": "573780618f5a11396ed8b40a1b01b394dfd7329c",
          "md5": "143fdc82c64b63187eb8358373c349aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "voidgradle-0.1.0.jar",
          "url": "voidgradle-0.1.0.jar",
          "size": 5057,
          "sha512": "070841ac9899df3170eef9d0ddf0f71ef8ac2024c311b064a337069710ed39deb4c4c59076189c655939b82b8662460447179b7ad97820f779d6e10d87cd52c6",
          "sha256": "0fc34bd0b4e8d1d0d3147312f2b84fa3c2a7c253729c45d52e6928f9044a58e1",
          "sha1": "573780618f5a11396ed8b40a1b01b394dfd7329c",
          "md5": "143fdc82c64b63187eb8358373c349aa"
        }
      ]
    }
  ]
}
